# Generated by Django 5.1 on 2024-08-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('app_username', models.CharField(max_length=50, unique=True)),
                ('app_password', models.CharField(max_length=50)),
                ('site_username', models.CharField(max_length=50)),
                ('site_password', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
    ]
