# Generated by Django 5.1.6 on 2025-02-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LR', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='selected_reports',
        ),
    ]
