# Generated by Django 5.1 on 2024-08-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LR', '0002_appuser_date_of_joining_appuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
