# Generated by Django 5.1 on 2024-08-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LR', '0003_dynamicexceldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DynamicExcelData',
        ),
    ]
