# Generated by Django 5.1 on 2024-09-30 07:12

from django.db import migrations, models
def set_default_password(apps, schema_editor):
    AppUser = apps.get_model('LR', 'AppUser')
    for user in AppUser.objects.all():
        user.app_password = 'default_password'  # Set a default password
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('LR', '0005_dynamicexceldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='app_password',
            field=models.CharField(max_length=50, default=''),
        ),
        migrations.RunPython(set_default_password),
    ]
